---
name: Bulid and test
on:
  workflow_call:
    inputs:
      os:
        description: array of OS in json format
        type: string
        required: true
jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ${{ fromJson(inputs.os) }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.3
      - name: Build
        run: go build -race  ./...
      - name: Test
        run: go test -race ./...
      - name: Test with permissions
        if: ${{ !contains(matrix.os, 'windows') }}
        run: |
          count=0
          while read -r line ; do
            [ -n "$(grep -l "Perm" $line)" ] && count=1 && break
          done < <(grep -R "build perm" --include="*_test.go" -l .)
          if [ $count == 1 ]; then
            echo "Found tests with permissions"
            sudo -E PATH="$PATH" bash -c "go test -race -run Perm ./... -tags=perm"
          fi
