---
name: Push docker image
on:
  workflow_call:
    secrets:
      docker-login:
        required: true
      docker-password:
        required: true
jobs:
  push:
    runs-on: ubuntu-latest
    env:
      DOCKER_USER: ${{ secrets.docker-login }}
      DOCKER_PASSWORD: ${{ secrets.docker-password }}
      ORG: networkservicemeshci
      CGO_ENABLED: 0
      NAME: ${{ github.event.repository.name }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.23.3
      - name: Build ${NAME}:${GITHUB_SHA::8} image
        run: docker build . -t "${ORG}/${NAME}:${GITHUB_SHA::8}" --target runtime
      - name: Build ${NAME}:latest image
        run: docker build . -t "${ORG}/${NAME}" --target runtime
      - name: Push ${NAME} images
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
          docker push "${ORG}/${NAME}:${GITHUB_SHA::8}"
          docker image rm "${ORG}/${NAME}:${GITHUB_SHA::8}"
          docker push "${ORG}/${NAME}"
          docker image rm "${ORG}/${NAME}"
